### ISSUE TITLE
Function without Netdata Cloud

### ISSUE THREAD

**Issue by sw5ciprl** [netdata/netdata-grafana-datasource-plugin#20]
In its current state, the Grafana plugin works through Netdata Cloud. However, if every node exposes its own metric data, and it can be organized via a registry, can it be possible to make this plugin work by connecting to the registry node?

**Comment by hugovalente-pm** [comment]
one of the reasons, besides promoting more Cloud, is that there should be away to ensure you have authorization access to the agents.
if this was simply exposed from the agent how would the authentication/authorization be dealt?

there is actually an active discussion on this topic [here](https://github.com/netdata/netdata/discussions/16136)

**Comment by beh-10257** [comment]
my use case is basically on the same laptop I want to have netdata and grafana and just see my netdata information from grafana
this is already possible by exporting information from netdata to promethius to grafana so why not make life easier

**Comment by marvinruder** [comment]
> Do you mean to make it work with a parent node instead of Netdata cloud? If true, then that would be awesome.

I have succeeded in configuring this plugin to directly access a local Netdata instance.

> Maybe it is as simple as changing the URL in [src/plugin.json](https://github.com/netdata/netdata-grafana-datasource-plugin/blob/1b9a493fc2848bc1be187d94c49414b8b9195d2b/src/plugin.json) 🤔

@caleno In addition to changing the URL there, I had to remove all logic related to spaces and rooms and switch some requests from POST to GET since only GET requests appear to be supported by Netdata instances (as documented in the [official Netdata API documentation](https://learn.netdata.cloud/api#/)), but most of it was pretty straightforward.

Using the changes from [my pull request](https://github.com/marvinruder/netdata-local-grafana-datasource-plugin/pull/1), you can try out my implementation today. I plan to publish my changes as a separate Grafana plugin, but will have to make sure not to violate intellectual property rights of Netdata Inc. by doing so.
